version: "2"

volumes:
  kerberosagent_recordings:
  kerberosagent_snapshots:
  kerberosagent_config:

services:
  agent:
    image: bh.cr/kerberos_io/agent
    network_mode: host
    tty: true
    restart: always
    volumes:
      - "kerberosagent_recordings:/home/agent/data/recordings:rw"
      - "kerberosagent_snapshots:/home/agent/data/snapshots:rw"
      - "kerberosagent_config:/home/agent/data/config:rw"
  camera:
    build: ./camera
    network_mode: host
    privileged: true
    restart: always
    environment:
      - MTX_PATHS_CAM_SOURCE=rpiCamera
